import type {
  HeadToHead,
  MatchEvent,
  OddsPoint,
  Recommendation,
  Standing,
  Team,
  WorldCupMatch,
} from '../types';

const brazil: Team = {
  id: 'team-1',
  name: 'Brazil',
  slug: 'brazil',
  short: 'BRA',
  country: 'Brazil',
  ranking: 1,
  badgeUrl: 'https://images.unsplash.com/photo-1548451586-1820b241b12b?auto=format&fit=crop&w=200&q=80',
};

const france: Team = {
  id: 'team-2',
  name: 'France',
  slug: 'france',
  short: 'FRA',
  country: 'France',
  ranking: 3,
  badgeUrl: 'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=200&q=80',
};

export const featuredMatches: MatchEvent[] = [
  {
    id: 'match-001',
    homeTeam: brazil,
    awayTeam: france,
    league: 'World Cup Group Stage',
    stage: 'Group A',
    kickOff: '2026-12-01T20:00:00Z',
    status: 'Live',
    homeScore: 1,
    awayScore: 0,
    weather: 'Clear, 22°C',
    stadium: 'Lusail Iconic Stadium',
    aiPrediction: {
      home: 0.48,
      draw: 0.27,
      away: 0.25,
      riskRating: 'Medium',
      summary: 'Brazil dominates possession and edge in attack, but France counter quickly.',
    },
    analytics: {
      xG: { home: 1.72, away: 0.81 },
      possession: { home: 57, away: 43 },
      shots: { home: 11, away: 6 },
      corners: { home: 5, away: 2 },
      defense: { interceptions: 12, tackles: 18 },
    },
    oddsHistory: [
      { time: '10:00', home: 1.95, draw: 3.50, away: 4.10 },
      { time: '12:00', home: 1.90, draw: 3.45, away: 4.20 },
      { time: '14:00', home: 1.85, draw: 3.38, away: 4.40 },
      { time: '16:00', home: 1.82, draw: 3.30, away: 4.55 },
    ],
    history: [
      { id: 'h1', date: '2025-11-12', home: 'Brazil', away: 'France', score: '2-1', competition: 'Friendly' },
      { id: 'h2', date: '2023-06-22', home: 'France', away: 'Brazil', score: '1-1', competition: 'International Cup' },
    ],
  },
  {
    id: 'match-002',
    homeTeam: {
      id: 'team-3',
      name: 'Argentina',
      slug: 'argentina',
      short: 'ARG',
      country: 'Argentina',
      ranking: 2,
      badgeUrl: 'https://images.unsplash.com/photo-1541461450-1f2a3bcbc88f?auto=format&fit=crop&w=200&q=80',
    },
    awayTeam: {
      id: 'team-4',
      name: 'Germany',
      slug: 'germany',
      short: 'GER',
      country: 'Germany',
      ranking: 5,
      badgeUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=200&q=80',
    },
    league: 'World Cup Group Stage',
    stage: 'Group B',
    kickOff: '2026-12-01T22:00:00Z',
    status: 'Scheduled',
    weather: 'Cloudy, 18°C',
    stadium: 'Education City Stadium',
    aiPrediction: {
      home: 0.42,
      draw: 0.29,
      away: 0.29,
      riskRating: 'High',
      summary: 'Small margin between giants; any defensive lapse may shift outcome.',
    },
    analytics: {
      xG: { home: 1.25, away: 1.33 },
      possession: { home: 49, away: 51 },
      shots: { home: 9, away: 10 },
      corners: { home: 4, away: 6 },
      defense: { interceptions: 15, tackles: 20 },
    },
    oddsHistory: [
      { time: '10:00', home: 2.10, draw: 3.30, away: 3.20 },
      { time: '12:00', home: 2.05, draw: 3.28, away: 3.24 },
      { time: '14:00', home: 2.02, draw: 3.25, away: 3.28 },
      { time: '16:00', home: 1.98, draw: 3.22, away: 3.35 },
    ],
    history: [
      { id: 'h3', date: '2024-09-08', home: 'Argentina', away: 'Germany', score: '1-1', competition: 'International Friendly' },
    ],
  },
];

export const recommendations: Recommendation[] = [
  {
    label: 'Most Stable',
    title: 'Brazil vs France - Under 2.5',
    odds: '1.88',
    confidence: 0.84,
    note: 'AI评估为低风险稳定单场。',
    highlight: '场面控制 + 防守效率',
  },
  {
    label: 'High Odds',
    title: 'Germany +0.5 Asian Handicap',
    odds: '2.20',
    confidence: 0.72,
    note: 'AI捕捉到统一赔率回落后价值点。',
    highlight: '阵容健康 + 反击机会',
  },
  {
    label: 'Upset Alert',
    title: 'Argentina vs Germany - Draw',
    odds: '3.28',
    confidence: 0.53,
    note: '风险预警：比赛平局概率上升。',
    highlight: '赔率异常 + 历史低分率',
  },
];

export const worldCupStandings: Standing[] = [
  { group: 'A', team: 'Brazil', played: 1, win: 1, draw: 0, loss: 0, points: 3 },
  { group: 'A', team: 'France', played: 1, win: 0, draw: 0, loss: 1, points: 0 },
  { group: 'B', team: 'Argentina', played: 1, win: 0, draw: 1, loss: 0, points: 1 },
  { group: 'B', team: 'Germany', played: 1, win: 0, draw: 1, loss: 0, points: 1 },
];

export const worldCupMatches: WorldCupMatch[] = [
  { id: 'wc-01', home: 'Brazil', away: 'France', time: '20:00', status: 'Live', score: '1-0', stage: 'Group A' },
  { id: 'wc-02', home: 'Argentina', away: 'Germany', time: '22:00', status: 'Upcoming', stage: 'Group B' },
  { id: 'wc-03', home: 'Portugal', away: 'Spain', time: '18:30', status: 'Finished', score: '2-2', stage: 'Group C' },
];

export const jingcaiMatches: MatchEvent[] = [
  {
    id: 'jc-01',
    homeTeam: { id: 'team-11', name: '赫尔辛基', slug: 'helsinki', short: 'HEL', country: 'Finland', ranking: 12, badgeUrl: '' },
    awayTeam: { id: 'team-12', name: 'IFK 哥德堡', slug: 'ifk-goteborg', short: 'IFK', country: 'Sweden', ranking: 35, badgeUrl: '' },
    league: '瑞典超级联赛',
    stage: '第2场',
    kickOff: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '阴',
    stadium: '赫尔辛基主场',
    aiPrediction: {
      home: 0.35,
      draw: 0.28,
      away: 0.37,
      riskRating: 'Medium',
      summary: 'AI 分析认为客队更擅长反击，予以客胜提示。',
    },
    analytics: { xG: { home: 1.1, away: 1.3 }, possession: { home: 48, away: 52 }, shots: { home: 9, away: 11 }, corners: { home: 3, away: 5 }, defense: { interceptions: 10, tackles: 13 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-02',
    homeTeam: { id: 'team-13', name: '克雷莫纳', slug: 'cremonese', short: 'CRE', country: 'Italy', ranking: 18, badgeUrl: '' },
    awayTeam: { id: 'team-14', name: '拉齐奥', slug: 'lazio', short: 'LAZ', country: 'Italy', ranking: 8, badgeUrl: '' },
    league: '意甲',
    stage: '第3场',
    kickOff: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '多云',
    stadium: '克雷莫纳球场',
    aiPrediction: {
      home: 0.22,
      draw: 0.33,
      away: 0.45,
      riskRating: 'High',
      summary: 'AI 认为拉齐奥控球更稳定，推荐客胜。',
    },
    analytics: { xG: { home: 0.9, away: 1.6 }, possession: { home: 42, away: 58 }, shots: { home: 7, away: 14 }, corners: { home: 2, away: 7 }, defense: { interceptions: 9, tackles: 15 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-03',
    homeTeam: { id: 'team-15', name: '哈马比', slug: 'hammarby', short: 'HAM', country: 'Sweden', ranking: 11, badgeUrl: '' },
    awayTeam: { id: 'team-16', name: '布罗马波卡纳', slug: 'brommapojkarna', short: 'BP', country: 'Sweden', ranking: 22, badgeUrl: '' },
    league: '瑞典超级联赛',
    stage: '第4场',
    kickOff: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '晴',
    stadium: '哈马比体育场',
    aiPrediction: {
      home: 0.46,
      draw: 0.30,
      away: 0.24,
      riskRating: 'Medium',
      summary: 'AI 识别主场优势明显，推荐主胜。',
    },
    analytics: { xG: { home: 1.4, away: 0.9 }, possession: { home: 55, away: 45 }, shots: { home: 11, away: 8 }, corners: { home: 6, away: 3 }, defense: { interceptions: 11, tackles: 14 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-04',
    homeTeam: { id: 'team-17', name: '吉达联', slug: 'al-ittihad', short: 'JED', country: 'Saudi', ranking: 13, badgeUrl: '' },
    awayTeam: { id: 'team-18', name: '拉斯永恒', slug: 'al-rass', short: 'RAS', country: 'Saudi', ranking: 15, badgeUrl: '' },
    league: '沙特职业联赛',
    stage: '第7场',
    kickOff: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '热',
    stadium: '吉达联体育场',
    aiPrediction: {
      home: 0.51,
      draw: 0.28,
      away: 0.21,
      riskRating: 'Low',
      summary: 'AI 认为主队进攻更强，推荐主胜。',
    },
    analytics: { xG: { home: 1.7, away: 0.8 }, possession: { home: 60, away: 40 }, shots: { home: 13, away: 6 }, corners: { home: 7, away: 2 }, defense: { interceptions: 12, tackles: 14 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-05',
    homeTeam: { id: 'team-19', name: '罗马', slug: 'roma', short: 'ROM', country: 'Italy', ranking: 6, badgeUrl: '' },
    awayTeam: { id: 'team-20', name: '佛罗伦萨', slug: 'fiorentina', short: 'FIO', country: 'Italy', ranking: 10, badgeUrl: '' },
    league: '意甲',
    stage: '第8场',
    kickOff: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '晴',
    stadium: '奥林匹克球场',
    aiPrediction: {
      home: 0.42,
      draw: 0.33,
      away: 0.25,
      riskRating: 'Medium',
      summary: 'AI 预计主队造势更强，建议主胜。',
    },
    analytics: { xG: { home: 1.5, away: 1.2 }, possession: { home: 54, away: 46 }, shots: { home: 10, away: 9 }, corners: { home: 5, away: 4 }, defense: { interceptions: 13, tackles: 17 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-06',
    homeTeam: { id: 'team-21', name: '埃弗顿', slug: 'everton', short: 'EVE', country: 'England', ranking: 14, badgeUrl: '' },
    awayTeam: { id: 'team-22', name: '曼城', slug: 'man-city', short: 'MCI', country: 'England', ranking: 1, badgeUrl: '' },
    league: '英超',
    stage: '第9场',
    kickOff: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '阵雨',
    stadium: '古迪逊公园',
    aiPrediction: {
      home: 0.18,
      draw: 0.25,
      away: 0.57,
      riskRating: 'High',
      summary: 'AI 认为曼城实力差距明显，建议客胜。',
    },
    analytics: { xG: { home: 0.8, away: 2.1 }, possession: { home: 40, away: 60 }, shots: { home: 7, away: 18 }, corners: { home: 2, away: 9 }, defense: { interceptions: 11, tackles: 17 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-07',
    homeTeam: { id: 'team-23', name: '塞维利亚', slug: 'sevilla', short: 'SEV', country: 'Spain', ranking: 9, badgeUrl: '' },
    awayTeam: { id: 'team-24', name: '皇家社会', slug: 'real-sociedad', short: 'RSO', country: 'Spain', ranking: 5, badgeUrl: '' },
    league: '西甲',
    stage: '第10场',
    kickOff: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '晴',
    stadium: '拉蒙·桑切斯·皮斯胡安',
    aiPrediction: {
      home: 0.40,
      draw: 0.34,
      away: 0.26,
      riskRating: 'Medium',
      summary: 'AI 判断塞维利亚主场更有竞争力，推荐主胜。',
    },
    analytics: { xG: { home: 1.3, away: 1.1 }, possession: { home: 52, away: 48 }, shots: { home: 11, away: 10 }, corners: { home: 5, away: 4 }, defense: { interceptions: 12, tackles: 16 } },
    oddsHistory: [],
    history: [],
  },
  {
    id: 'jc-08',
    homeTeam: { id: 'team-25', name: '阿森纳', slug: 'arsenal', short: 'ARS', country: 'England', ranking: 2, badgeUrl: '' },
    awayTeam: { id: 'team-26', name: '切尔西', slug: 'chelsea', short: 'CHE', country: 'England', ranking: 7, badgeUrl: '' },
    league: '英超',
    stage: '第11场',
    kickOff: new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString(),
    status: 'Not Started',
    weather: '晴',
    stadium: '酋长球场',
    aiPrediction: {
      home: 0.44,
      draw: 0.31,
      away: 0.25,
      riskRating: 'Medium',
      summary: 'AI 认为阿森纳攻击力更占优，推荐主胜。',
    },
    analytics: { xG: { home: 1.6, away: 1.0 }, possession: { home: 58, away: 42 }, shots: { home: 13, away: 8 }, corners: { home: 6, away: 3 }, defense: { interceptions: 12, tackles: 14 } },
    oddsHistory: [],
    history: [],
  },
];

export const parlayAdvice = [
  {
    name: 'Remove Germany vs Argentina',
    risk: 'High',
    impact: 'Reduce parlay volatility by 18%',
    suggestion: '该场比赛已进入爆冷预警区，建议从组合中剔除。',
  },
  {
    name: 'Keep Brazil vs France',
    risk: 'Medium',
    impact: '稳定胜率 +8%',
    suggestion: 'AI认为该场具备强攻击价值与数据支撑。',
  },
  {
    name: 'Balance with Portugal',
    risk: 'Low',
    impact: '提高串关稳定性',
    suggestion: '加入进攻型低风险场次，提升组合命中率。',
  },
];

export const parlayOutcome = {
  title: '智能优化后串关组合',
  changedOdds: '5.6 → 4.8',
  winProbability: 0.63,
  riskTier: 'Balanced' as const,
};

export const allMatches: MatchEvent[] = featuredMatches;
